import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "@components/Card";
import { DataTable } from "@components/Table";
import React from "react";
import CardContent from "@components/CardContent";
import CardMedia from "@components/CardMedia";
import FavoriteOverlay from "@components/FavoriteOverlay";
import Slider from "@components/Slider";
import Typography from "@components/Typography";
import Deck from "@components/Deck";
import { DeckItem } from "@components/Deck/Deck";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Deck onVote={(item: any, vote: any) => console.log(item.props, vote)}>
          <DeckItem value="waffles" whileTap={1.15}>
            🧇
          </DeckItem>
          <DeckItem value="pancakes" whileTap={1.15}>
            🥞
          </DeckItem>
          <DeckItem value="donuts" whileTap={1.15}>
            🍩
          </DeckItem>
        </Deck>

        <Card title="Header">test</Card>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
