import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "@components/Card";
import { DataTable } from "@components/Table";
import React from "react";
import CardContent from "@components/CardContent";
import CardMedia from "@components/CardMedia";
import FavoriteOverlay from "@components/FavoriteOverlay";
import Slider from "@components/Slider";
import Typography from "@components/Typography";
import Deck from "@components/Deck";
import { DeckItem } from "@components/Deck/Deck";
import Layout from "@components/Layouts/Layout/Layout";
import HomePageTop from "@components/Layouts/HomePageTop";
import SummaryItem from "@components/SummaryItem";
import SummaryItemPicture from "@components/SummaryItem/SummaryItemPicture";
import SummaryItemText from "@components/SummaryItem/SummaryItemText";
import SummaryItemTitle from "@components/SummaryItem/SummaryItemTitle";
import SummaryItemStyles from "@components/SummaryItem/SummaryItem.module.css";
import MostPopularArticles from "@components/MostPopularArticles";
import { articles } from "@components/MostPopularArticles/articles";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto relative w-full items-center justify-center max-w-7xl">
        <div className="mt-20">
          <HomePageTop>
            <HomePageTop.LeftSide>
              <div className="grid grid-cols-1 gap-10">
                <Card>
                  <CardMedia src="https://res.cloudinary.com/film-it/image/upload/v1632166012/james-gandolfini-not-fade-away-580.jpg.webp" />
                  <Typography.Text className="text-red-800 uppercase">
                    Prehistory Dept.
                  </Typography.Text>
                  <Typography.Title level={3}>
                    Alessandro Nivola’s “Sopranos” Time Travel
                  </Typography.Title>

                  <CardContent>
                    The actor visits the old stomping ground of the mafioso
                    Richie (the Boot) Boiardo.
                    <div className="text-sm font-semibold my-6">
                      By Kyle Chayka
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardMedia src="https://res.cloudinary.com/film-it/image/upload/v1632166012/james-gandolfini-not-fade-away-580.jpg.webp" />
                  <Typography.Text className="text-red-800 uppercase">
                    Prehistory Dept.
                  </Typography.Text>
                  <Typography.Title level={3}>
                    Alessandro Nivola’s “Sopranos” Time Travel
                  </Typography.Title>

                  <CardContent>
                    The actor visits the old stomping ground of the mafioso
                    Richie (the Boot) Boiardo.
                    <div className="text-sm font-semibold my-6">
                      By Kyle Chayka
                    </div>
                  </CardContent>
                </Card>
              </div>
            </HomePageTop.LeftSide>
            <HomePageTop.Lead>
              <div className="grid grid-cols-1 gap-10">
                <Card>
                  <CardMedia src="https://res.cloudinary.com/film-it/image/upload/v1633120463/original.webp" />
                  <Typography.Title className="mt-3" level={2}>
                    The Conservatives Dreading—And Preparing for—Civil War
                  </Typography.Title>

                  <CardContent className="">
                    A faction of the right believes America has been riven into
                    two countries. The Claremont Institute is building the
                    intellectual architecture for whatever comes next.
                    <div className="text-sm font-semibold my-6">Emma Green</div>
                  </CardContent>
                </Card>
                <SummaryItem
                  className="mb-10 border-t"
                  borderRight={false}
                  borderBottom
                >
                  <div className={SummaryItemStyles["mgui-summary-item-grid"]}>
                    <div className="flex flex-col">
                      <SummaryItemTitle
                        title="Damian Lewis Discusses the Future of ‘Billions’"
                        subTitle="Television"
                      />
                      <SummaryItemText className="p-0 leading-7">
                        In an interview, the actor talked about his character’s
                        big twist and what it means for the Showtime series and
                        his career.
                      </SummaryItemText>
                    </div>
                    <SummaryItemPicture
                      className="w-20 h-14 self-center ml-auto"
                      imageUrl={`https://res.cloudinary.com/film-it/image/upload/v1632983797/211004_r39115web.webp`}
                    />
                    <Typography.Text className="font-semibold mt-3">
                      By Alexandra Schwartz
                    </Typography.Text>
                  </div>
                </SummaryItem>
              </div>
            </HomePageTop.Lead>
            <HomePageTop.RightSide>
              <div className="grid grid-cols-1 gap-10">
                <SummaryItem className="mb-10" borderRight={false} borderBottom>
                  <div className={SummaryItemStyles["mgui-summary-item-grid"]}>
                    <div className="flex flex-col">
                      <SummaryItemTitle title="" subTitle="Books" />
                      <SummaryItemText className="p-0 leading-7">
                        Shaping the Sexual Desires that Shape Us
                      </SummaryItemText>
                    </div>
                    <SummaryItemPicture
                      className="w-20 h-14 self-center ml-auto"
                      imageUrl={`https://res.cloudinary.com/film-it/image/upload/v1632983797/211004_r39115web.webp`}
                    />
                    <Typography.Text className="font-semibold mt-3">
                      By Alexandra Schwartz
                    </Typography.Text>
                  </div>
                </SummaryItem>
                <SummaryItem className="mb-10" borderRight={false} borderBottom>
                  <div className={SummaryItemStyles["mgui-summary-item-grid"]}>
                    <div className="flex flex-col">
                      <SummaryItemTitle title="" subTitle="Infinite Scroll" />
                      <SummaryItemText className="p-0 leading-7">
                        Corporate America Is Failing Its Most Important Climate
                        Test Yet
                      </SummaryItemText>
                    </div>
                    <SummaryItemPicture
                      className="w-20 h-20 self-center ml-auto"
                      imageUrl={`https://res.cloudinary.com/film-it/image/upload/v1632983838/chayka_americancore.webp`}
                    />
                  </div>
                  <Typography.Text className="font-semibold mt-3">
                    By Alexandra Schwartz
                  </Typography.Text>
                </SummaryItem>
                <SummaryItem className="mb-10" borderRight={false} borderBottom>
                  <div className={SummaryItemStyles["mgui-summary-item-grid"]}>
                    <div className="flex flex-col">
                      <SummaryItemTitle title="" subTitle="Books" />
                      <SummaryItemText className="p-0 leading-7">
                        Shaping the Sexual Desires that Shape Us
                      </SummaryItemText>
                    </div>
                    <SummaryItemPicture
                      className="w-20 h-14 self-center ml-auto"
                      imageUrl={`https://res.cloudinary.com/film-it/image/upload/v1632983797/211004_r39115web.webp`}
                    />
                    <Typography.Text className="font-semibold mt-3">
                      By Alexandra Schwartz
                    </Typography.Text>
                  </div>
                </SummaryItem>
                <SummaryItem className="mb-10" borderRight={false} borderBottom>
                  <div className={SummaryItemStyles["mgui-summary-item-grid"]}>
                    <div className="flex flex-col">
                      <SummaryItemTitle title="" subTitle="Infinite Scroll" />
                      <SummaryItemText className="p-0 leading-7">
                        Corporate America Is Failing Its Most Important Climate
                        Test Yet
                      </SummaryItemText>
                    </div>
                    <SummaryItemPicture
                      className="w-20 h-20 self-center ml-auto"
                      imageUrl={`https://res.cloudinary.com/film-it/image/upload/v1632983838/chayka_americancore.webp`}
                    />
                  </div>
                  <Typography.Text className="font-semibold mt-3">
                    By Alexandra Schwartz
                  </Typography.Text>
                </SummaryItem>
                <SummaryItem className="mb-10" borderRight={false} borderBottom>
                  <div className={SummaryItemStyles["mgui-summary-item-grid"]}>
                    <div className="flex flex-col">
                      <SummaryItemTitle title="" subTitle="Infinite Scroll" />
                      <SummaryItemText className="p-0 leading-7">
                        Corporate America Is Failing Its Most Important Climate
                        Test Yet
                      </SummaryItemText>
                    </div>
                    <SummaryItemPicture
                      className="w-20 h-20 self-center ml-auto"
                      imageUrl={`https://res.cloudinary.com/film-it/image/upload/v1632983838/chayka_americancore.webp`}
                    />
                  </div>
                  <Typography.Text className="font-semibold mt-3">
                    By Alexandra Schwartz
                  </Typography.Text>
                </SummaryItem>
              </div>
            </HomePageTop.RightSide>
          </HomePageTop>
        </div>

        <div className="grid grid-cols-4 gap-4 mt-10">
          <Card>
            <CardMedia src="https://res.cloudinary.com/film-it/image/upload/v1632166012/james-gandolfini-not-fade-away-580.jpg.webp" />
            <Typography.Text className="text-red-800 uppercase">
              Prehistory Dept.
            </Typography.Text>
            <Typography.Title level={3}>
              Alessandro Nivola’s “Sopranos” Time Travel
            </Typography.Title>

            <CardContent>
              The actor visits the old stomping ground of the mafioso Richie
              (the Boot) Boiardo.
              <div className="text-sm font-semibold my-6">By Kyle Chayka</div>
            </CardContent>
          </Card>
          <Card>
            <CardMedia src="https://res.cloudinary.com/film-it/image/upload/v1632165317/Alarcon-Abimael.webp" />

            <Typography.Text className="text-red-800 uppercase">
              Prehistory Dept.
            </Typography.Text>
            <Typography.Title level={3}>
              Alessandro Nivola’s “Sopranos” Time Travel
            </Typography.Title>

            <CardContent>
              The actor visits the old stomping ground of the mafioso Richie
              (the Boot) Boiardo.
              <div className="text-sm font-semibold my-6">By Kyle Chayka</div>
            </CardContent>
          </Card>
          <Card>
            <CardMedia src="https://res.cloudinary.com/film-it/image/upload/v1632161978/alan-w-RyZSDhYyFFQ-unsplash.jpg" />

            <Typography.Text className="text-red-800 uppercase">
              Prehistory Dept.
            </Typography.Text>
            <Typography.Title level={3}>
              Alessandro Nivola’s “Sopranos” Time Travel
            </Typography.Title>

            <CardContent>
              The actor visits the old stomping ground of the mafioso Richie
              (the Boot) Boiardo.
              <div className="text-sm font-semibold my-6">By Kyle Chayka</div>
            </CardContent>
          </Card>
          <Card>
            <CardMedia src="https://res.cloudinary.com/film-it/image/upload/v1632165845/laurenz-heymann-VkfhJLz5SMQ-unsplash.jpg" />

            <Typography.Text className="text-red-800 uppercase">
              Infinite Scroll
            </Typography.Text>
            <Typography.Title level={3}>
              How Epic Games Made a Dent in Apple’s App Store Domination
            </Typography.Title>

            <CardContent>
              In a calculated bit of legal trolling, the video-game company has
              landed a victory with major implications for users and developers
              alike.
              <div className="text-sm font-semibold my-6">By Kyle Chayka</div>
            </CardContent>
          </Card>
        </div>
        <MostPopularArticles articles={articles} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

Home.Layout = Layout;

export default Home;
